### ISSUE TITLE
reconstruction on YFCC dataset

### ISSUE THREAD

**Issue by Shuyan98** [lixiangpengcs/Self-Supervised-Video-Hashing#2]
Hello, I managed to reconstruct the result on FCVID with the help of your code, but I met trouble on YFCC.  E.g. According to the paper, the reported MAP@5 for 128-bits on YFCC was about 0.38, but I only got 0.18. My training process for YFCC is like this: I recursively used the 9 training splits to feed the network, and the order of the training splits was randomly chosen for each epoch. For retrieval, I concat the 2 test splits as a whole test matrix.  I kept the parameters the same with your default setting. Could you please inform me of your training details on YFCC dataset? Thank you very much.

**Comment by lixiangpengcs** [comment]
I am sorry to see this information too late. And I have replied your e-mail several days ago.

**Comment by lpdone** [comment]
> I am sorry to see this information too late. And I have replied your e-mail several days ago.

可以发我一份细节吗？另外，YFCC的标签在哪里可以看到？谢谢！

**Comment by lixiangpengcs** [comment]
Sorry, the email is lost and the labels can also be found at @Lily1994. Hello, Lily, I forget the details about how to use get the labels of the YFCC dataset. Could you provide several details about the YFCC labels to him @rovgtjktm66?
