### ISSUE TITLE
SSVH.py 

### ISSUE THREAD

**Issue by Zxzzzzz** [lixiangpengcs/Self-Supervised-Video-Hashing#3]
Hello, I didn't find SSVH.py in your submitted codes. I 've got the datasets, but what should I do to run these codes? Thanks.

**Comment by lixiangpengcs** [comment]
I am sorry for this mistake. The Pairwise-BLSTM.py is SSVH.py indeed. This code is uploaded 2 years ago and you need to configure your Theano environment as suggested.
